config/routes.rb
Rails.application.routes.draw do
  get 'contact/index'

  root 'welcome#index'

  get 'welcome/index'

  get 'welcome/about', as: 'about'
  get 'welcome/services', as: 'services'
  get 'contact/contact_us', as: 'contact'

  post 'contact/create'

  get 'welcome/p404'
  get 'welcome/portfolio1col'
  get 'welcome/portfolio2col'
  get 'welcome/portfolio3col'
  get 'welcome/portfolio4col'
  get 'welcome/portfolioitem'
  get 'welcome/bloghome1'
  get 'welcome/bloghome2'
  get 'welcome/blogpost'
  get 'welcome/sidebar'
  get 'welcome/faq'
  get 'welcome/pricing'
  get 'welcome/fullwidth'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true
  VALID_PHONE_NUMBER_REGEX = /\A(\+\d{1,2})?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}\z/
  validates :phone_number, length: {maximum: 17}, format: { with: VALID_PHONE_NUMBER_REGEX }, allow_nil: true
  validates :message, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, length: { maximum: 50 }, format: { with: VALID_EMAIL_REGEX }, allow_nil: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end

  def contact_us
    @contact = Contact.new
  end

  # def create
  #   @contact = Contact.new(contact_params)
  #   respond_to do |format|
  #       if @contact.save
  #         format.html { redirect_to contact_url, notice: 'this should work.' }
  #         format.json { render :show, status: :created, location: @contact }
  #       else
  #         format.html { render :contact_us }
  #         format.json { render json: @contact.errors, status: :unprocessable_entity }
  #       end
  #     end
  # end



  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactNotifier.requester(@contact).deliver
      flash[:success] = "Thanks for contacting us, we will get in touch with you shortly." #bootstrap thing/flash notice
      redirect_to contact_path
    else
      # flash[:danger] = "no good" #bootstrap thing/flash notice
      render 'contact_us'
    end
  end

  private

    def contact_params
      params.require(:contact).permit(:name, :email, :message, :phone_number)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def services
  end

  def contact
  end

  def p404
  end

  def portfolio1col
  end

  def portfolio2col
  end

  def portfolio2col
  end

  def portfolio4col
  end

  def portfolioitem
  end

  def bloghome1
  end

  def bloghome2
  end

  def blogpost
  end

  def sidebar
  end

  def faq
  end

  def pricing
  end

  def fullwidth
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def is_active?(link_path)
   current_page?(link_path) ? "active" : ""
  end

  def is_portfolio_active?
      array = ["/welcome/portfolio1col", "/welcome/portfolio2col", "/welcome/portfolio3col", "/welcome/portfolio4col", "/welcome/portfolioitem"]
      array.each do |path|
      if current_page?(path)
        return "dropdown active"
      else
        "dropdown"
      end
    end
  end

  def is_blog_active?
      array = ['/welcome/bloghome1', '/welcome/bloghome2', '/welcome/blogpost']
      array.each do |path|
      if current_page?(path)
        return "dropdown active"
      else
        "dropdown"
      end
    end
  end

  def is_otherpages_active?
      array = ['/welcome/fullwidth', '/welcome/sidebar', '/welcome/faq', '/welcome/p404', '/welcome/pricing']
      array.each do |path|
      if current_page?(path)
        return "dropdown active"
      else
        "dropdown"
      end
    end
  end

end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contact/_original_contact.html.erb
<!-- Contact Form -->
<!-- In order to set the email address and subject line for the contact form go to the bin/contact_me.php file. -->
<div class="row">
    <div class="col-md-8">
        <h3>Send us a Message</h3>
        <form name="sentMessage" id="contactForm" novalidate>
            <div class="control-group form-group">
                <div class="controls">
                    <label>Full Name:</label>
                    <input type="text" class="form-control" id="name" required data-validation-required-message="Please enter your name.">
                    <!-- <p class="help-block"></p> -->
                </div>
            </div>
            <div class="control-group form-group">
                <div class="controls">
                    <label>Phone Number:</label>
                    <input type="tel" class="form-control" id="phone" required data-validation-required-message="Please enter your phone number.">
                </div>
            </div>
            <div class="control-group form-group">
                <div class="controls">
                    <label>Email Address:</label>
                    <input type="email" class="form-control" id="email" required data-validation-required-message="Please enter your email address.">
                </div>
            </div>
            <div class="control-group form-group">
                <div class="controls">
                    <label>Message:</label>
                    <textarea rows="10" cols="100" class="form-control" id="message" required data-validation-required-message="Please enter your message" maxlength="999" style="resize:none"></textarea>
                </div>
            </div>
            <div id="success"></div>
            <!-- For success/fail messages -->
            <button type="submit" class="btn btn-primary">Send Message</button>
        </form>
    </div>

</div>
<!-- /.row -->

</div>
<!-- /.container -->


<!-- Contact Form JavaScript -->
<!-- Do not edit these files! In order to set the email address and subject line for the contact form go to the bin/contact_me.php file. -->

<!-- <script src="js/jqBootstrapValidation.js"></script>
<script src="js/contact_me.js"></script> -->

app/views/contact/_practice.html.erb
<div class="row">
  <div class="col-md-8">
      <h3>Send us a Message</h3>
      <%= form_for :contact, url: contact_create_path, html: { id: "contactForm", name: "sentMessage", novalidate: "novalidate" } do |f| %>

      <!-- Removed errors that is usually here into top of page of contact_us for aesthetics -->


        <div class="control-group form-group">
          <div class="controls">
            <%= f.label :name, "Full Name:"%>
            <%= f.text_field :name, class: "form-control", id: "name" %>
          </div>
        </div>
        <div class="control-group form-group">
          <div class="controls">
            <%= f.label :phone_number, "Phone Number:"%>
            <%= f.telephone_field :phone_number, class: "form-control", id: "phone" %>
          </div>
        </div>
        <div class="control-group form-group">
          <div class="controls">
            <%= f.label :email, "Email Address:"%>
            <%= f.email_field :email, class: "form-control", id: "email" %>
          </div>
        </div>
        <div class="control-group form-group">
          <div class="controls">
            <%= f.label :message, "Message:"%>
            <%= f.text_area :message, class: "form-control", rows: "10", cols: "100", id: "message", maxlength: "999", style: "resize:none"  %>
          </div>
        </div>
        <div id="success"></div>
        <%= f.submit "Send Message", class: "btn btn-primary" %>
      <% end %>
  </div>
</div>




        <!-- <div class="row">
            <div class="col-md-8">
                <h3>Send us a Message</h3>
                <form name="sentMessage" id="contactForm" novalidate>
                    <div class="control-group form-group">
                        <div class="controls">
                            <label>Full Name:</label>
                            <input type="text" class="form-control" id="name" required data-validation-required-message="Please enter your name.">
                        </div>
                    </div> -->

app/views/contact/contact_us.html.erb
<% if @contact.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= pluralize(@contact.errors.count, "error") %> prohibited your message from being sent:

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>

        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Contact
                    <small>Subheading</small>
                </h1>
                <ol class="breadcrumb">
                    <li><a href="index.html">Home</a>
                    </li>
                    <li class="active">Contact</li>
                </ol>
            </div>
        </div>
        <!-- /.row -->

        <!-- Content Row -->
        <div class="row">
            <!-- Map Column -->
            <div class="col-md-8">
                <!-- Embedded Google Map -->
                <!-- <iframe width="100%" height="400px" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?hl=en&amp;ie=UTF8&amp;ll=37.0625,-95.677068&amp;spn=56.506174,79.013672&amp;t=m&amp;z=4&amp;output=embed"></iframe> -->
                <iframe width="100%" height="400px" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d5589.883926794494!2d-73.70021603156121!3d45.531373436877615!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4cc9187f7d660177%3A0xf0c6d13f40348c40!2sL&#39;%C3%89cole+Arm%C3%A9nienne+Sourp+Hagop!5e0!3m2!1sen!2sca!4v1463944937908"></iframe>
            </div>
            <!-- Contact Details Column -->
            <div class="col-md-4">
                <h3>Contact Details</h3>
                <p>
                    3481 Melrose Place<br>Beverly Hills, CA 90210<br>
                </p>
                <p><i class="fa fa-phone"></i>
                    <abbr title="Phone">P</abbr>: (123) 456-7890</p>
                <p><i class="fa fa-envelope-o"></i>
                    <abbr title="Email">E</abbr>: <a href="mailto:name@example.com">name@example.com</a>
                </p>
                <p><i class="fa fa-clock-o"></i>
                    <abbr title="Hours">H</abbr>: Monday - Friday: 9:00 AM to 5:00 PM</p>
                <ul class="list-unstyled list-inline list-social-icons">
                    <li>
                        <a href="#"><i class="fa fa-facebook-square fa-2x"></i></a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-linkedin-square fa-2x"></i></a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-twitter-square fa-2x"></i></a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-google-plus-square fa-2x"></i></a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- /.row -->

        <%= render partial: "practice" %>

app/views/contact/index.html.erb
<h1>Contact#index</h1>
<p>Find me in app/views/contact/index.html.erb</p>

app/views/contact_notifier/request.text.erb
ContactNotifier#request

<%= @greeting %>, find me in app/views/contact_notifier/request.text.erb

app/views/contact_notifier/requester.html.erb
<div class="control-group form-group">
  <div class="controls">
    <h3>Full Name:</h3>
    <p><%= @contact.name %></p>
  </div>
</div>
<div class="control-group form-group">
  <div class="controls">
    <h3>Phone Number:</h3>
    <p><%= @contact.phone_number %></p>
  </div>
</div>
<div class="control-group form-group">
  <div class="controls">
    <h3>Email Address:</h3>
    <p><%= @contact.email %></p>
  </div>
</div>
<div class="control-group form-group">
  <div class="controls">
    <h3>Message:</h3>
    <p><%= @contact.message %></p>
  </div>
</div>

app/views/layouts/_footer.html.erb
<hr>

<!-- Footer -->
<footer>
    <div class="row">
        <div class="col-lg-12">
            <p>Copyright &copy; Your Website 2016</p>
        </div>
    </div>
</footer>

</div>

app/views/layouts/_nav.html.erb
<!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "Group Shalex", welcome_index_path, class: "navbar-brand" %>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="<%= is_active?('/welcome/about') %>">
                        <%= link_to "About", about_path %>
                    </li>
                    <li class="<%= is_active?('/welcome/services') %>">
                        <%= link_to "Services", services_path %>
                    </li>
                    <li class="<%= is_active?('/contact/contact_us') %>">
                        <%= link_to "Contact", contact_path %>
                    </li>
                    <li class="<%= is_portfolio_active?%>">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Portfolio <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li class="<%= is_active?('/welcome/portfolio1col') %>">
                              <%= link_to "1 Column Portfolio", welcome_portfolio1col_path %>
                            </li>
                            <li class="<%= is_active?('/welcome/portfolio2col') %>">
                              <%= link_to "2 Column Portfolio", welcome_portfolio2col_path %>
                            </li>
                            <li class="<%= is_active?('/welcome/portfolio3col') %>">
                              <%= link_to "3 Column Portfolio", welcome_portfolio3col_path %>
                            </li>
                            <li class="<%= is_active?('/welcome/portfolio4col') %>">
                              <%= link_to "4 Column Portfolio", welcome_portfolio4col_path  %>
                            </li>
                            <li class="<%= is_active?('/welcome/portfolioitem') %>">
                              <%= link_to "Single Portfolio", welcome_portfolioitem_path %>
                            </li>
                        </ul>
                    </li>
                    <li class="<%= is_blog_active?%>">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Blog <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li class="<%= is_active?('/welcome/bloghome1') %>">
                              <%= link_to "Blog Home 1", welcome_bloghome1_path %>
                            </li>
                            <li class="<%= is_active?('/welcome/bloghome2') %>">
                              <%= link_to "Blog Home 2", welcome_bloghome2_path %>
                            </li>
                            <li class="<%= is_active?('/welcome/blogpost') %>">
                              <%= link_to "Blog Post", welcome_blogpost_path %>
                            </li>
                        </ul>
                    </li>
                    <li class="<%= is_otherpages_active?%>">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Other Pages <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li class="<%= is_active?('/welcome/fullwidth') %>">
                              <%= link_to "Full Width Page", welcome_fullwidth_path %>
                            </li>
                            <li class="<%= is_active?('/welcome/sidebar') %>">
                              <%= link_to "Sidebar Page", welcome_sidebar_path %>
                            </li>
                            <li class="<%= is_active?('/welcome/faq') %>">
                              <%= link_to "FAQ", welcome_faq_path %>
                            </li>
                            <li class="<%= is_active?('/welcome/p404') %>">
                                <%= link_to '404', welcome_p404_path %>
                            </li>
                            <li class="<%= is_active?('/welcome/pricing') %>">
                              <%= link_to "Pricing Table", welcome_pricing_path %>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Groupshalex</title>
  <!-- the following code is for internet explorer  -->
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"
    type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- the following code is to make it mobile and ipad friendly depending on the device -->



  <!-- Stuff copied from head section of index.html(.erb) header -->

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1"> <!-- A viewport controls how a webpage is displayed on a mobile device. Without a viewport, mobile devices will render the page at a typical desktop screen width, scaled to fit the screen. Setting a viewport gives control over the page's width and scaling on different devices. -->
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap Core CSS -->
    <!-- <link href="css/bootstrap.min.css" rel="stylesheet"> --> <!-- don't need this because all your stylesheet is already being linked from the stylesheet_link_tag above -->

    <!-- Custom CSS -->
    <!-- <link href="css/modern-business.css" rel="stylesheet"> --> <!-- don't need this because all your javascript is already being linked from the javascript_include_tag above -->

    <!-- Custom Fonts -->
    <!-- <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"> --> <!-- i think there is no need for this either as rails-awesome-fonts is taking care of this -->

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->


</head>
<body>
<%= render partial: "layouts/nav" %>

<% if current_page?(welcome_index_path) %>
  <%= render partial: "welcome/carousel" %>
<% end %>

<!-- Page Content -->
<div class="container">

  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %><button class="close" data-dismiss="alert">×</button></div>
  <% end %>

<%= yield %>

<%= render partial: "layouts/footer" %>

</div>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-78361051-3', 'auto');
  ga('send', 'pageview');

</script>

</body>
</html>

app/views/welcome/404.html.erb
        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">404
                    <small>Page Not Found</small>
                </h1>
                <ol class="breadcrumb">
                    <li><a href="index.html">Home</a>
                    </li>
                    <li class="active">404</li>
                </ol>
            </div>
        </div>
        <!-- /.row -->

        <div class="row">

            <div class="col-lg-12">
                <div class="jumbotron">
                    <h1><span class="error-404">404</span>
                    </h1>
                    <p>The page you're looking for could not be found. Here are some helpful links to get you back on track:</p>
                    <ul>
                        <li>
                            <a href="index.html">Home</a>
                        </li>
                        <li>
                            <a href="about.html">About</a>
                        </li>
                        <li>
                            <a href="services.html">Services</a>
                        </li>
                        <li>
                            <a href="contact.html">Contact</a>
                        </li>
                        <li>
                            Portfolio
                            <ul>
                                <li>
                                    <a href="portfolio-1-col.html">1 Column Portfolio</a>
                                </li>
                                <li>
                                    <a href="portfolio-2-col.html">2 Column Portfolio</a>
                                </li>
                                <li>
                                    <a href="portfolio-3-col.html">3 Column Portfolio</a>
                                </li>
                                <li>
                                    <a href="portfolio-4-col.html">4 Column Portfolio</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            Blog
                            <ul>
                                <li>
                                    <a href="blog-home-1.html">Blog Home 1</a>
                                </li>
                                <li>
                                    <a href="blog-home-2.html">Blog Home 2</a>
                                </li>
                                <li>
                                    <a href="blog-post.html">Blog Post</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            Other Pages
                            <ul>
                                <li>
                                    <a href="full-width-page.html">Full Width Page</a>
                                </li>
                                <li>
                                    <a href="sidebar.html">Sidebar Page</a>
                                </li>
                                <li>
                                    <a href="faq.html">FAQ</a>
                                </li>
                                <li>
                                    <a href="404.html">404 Page</a>
                                </li>
                                <li>
                                    <a href="pricing-table.html">Pricing Table</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>

        </div>

app/views/welcome/blog-home-2.html.erb
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Blog Home Two
                    <small>Subheading</small>
                </h1>
                <ol class="breadcrumb">
                    <li><a href="index.html">Home</a>
                    </li>
                    <li class="active">Blog Home Two</li>
                </ol>
            </div>
        </div>
        <!-- /.row -->

        <!-- Blog Post Row -->
        <div class="row">
            <div class="col-md-1 text-center">
                <p><i class="fa fa-camera fa-4x"></i>
                </p>
                <p>June 17, 2014</p>
            </div>
            <div class="col-md-5">
                <a href="blog-post.html">
                    <img class="img-responsive img-hover" src="http://placehold.it/600x300" alt="">
                </a>
            </div>
            <div class="col-md-6">
                <h3>
                    <a href="blog-post.html">Blog Post Title</a>
                </h3>
                <p>by <a href="#">Start Bootstrap</a>
                </p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
                <a class="btn btn-primary" href="blog-post.html">Read More <i class="fa fa-angle-right"></i></a>
            </div>
        </div>
        <!-- /.row -->

        <hr>

        <!-- Blog Post Row -->
        <div class="row">
            <div class="col-md-1 text-center">
                <p><i class="fa fa-film fa-4x"></i>
                </p>
                <p>June 17, 2014</p>
            </div>
            <div class="col-md-5">
                <a href="blog-post.html">
                    <img class="img-responsive img-hover" src="http://placehold.it/600x300" alt="">
                </a>
            </div>
            <div class="col-md-6">
                <h3><a href="blog-post.html">Blog Post Title</a>
                </h3>
                <p>by <a href="#">Start Bootstrap</a>
                </p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
                <a class="btn btn-primary" href="blog-post.html">Read More <i class="fa fa-angle-right"></i></a>
            </div>
        </div>
        <!-- /.row -->

        <hr>

        <!-- Blog Post Row -->
        <div class="row">
            <div class="col-md-1 text-center">
                <p><i class="fa fa-file-text fa-4x"></i>
                </p>
                <p>June 17, 2014</p>
            </div>
            <div class="col-md-5">
                <a href="blog-post.html">
                    <img class="img-responsive img-hover" src="http://placehold.it/600x300" alt="">
                </a>
            </div>
            <div class="col-md-6">
                <h3><a href="blog-post.html">Blog Post Title</a>
                </h3>
                <p>by <a href="#">Start Bootstrap</a>
                </p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
                <a class="btn btn-primary" href="blog-post.html">Read More <i class="fa fa-angle-right"></i></a>
            </div>
        </div>
        <!-- /.row -->

        <hr>

        <!-- Pager -->
        <div class="row">
            <ul class="pager">
                <li class="previous"><a href="#">&larr; Older</a>
                </li>
                <li class="next"><a href="#">Newer &rarr;</a>
                </li>
            </ul>
        </div>
        <!-- /.row -->

app/views/welcome/fullwidth.html.erb
        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Full Width Page
                    <small>Subheading</small>
                </h1>
                <ol class="breadcrumb">
                    <li><a href="index.html">Home</a>
                    </li>
                    <li class="active">Full Width Page</li>
                </ol>
            </div>
        </div>
        <!-- /.row -->

        <!-- Content Row -->
        <div class="row">
            <div class="col-lg-12">
                <p>Most of Start Bootstrap's unstyled templates can be directly integrated into the Modern Business template. You can view all of our unstyled templates on our website at <a href="http://startbootstrap.com/template-categories/unstyled">http://startbootstrap.com/template-categories/unstyled</a>.</p>
            </div>
        </div>
        <!-- /.row -->